"""first migration

Revision ID: b3a5ac9dd8c4
Revises: 1e4fd3934755
Create Date: 2021-10-02 00:13:04.085015

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3a5ac9dd8c4'
down_revision = '1e4fd3934755'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
